version: '3.8'

services:
  web:
    build: .
    container_name: sparkos_web
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOSTNAME=db
      - DB_USERNAME=root
      - DB_PASSWORD=sparkos_root_pass
      - DB_DATABASE=sistema
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: sparkos_db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=sistema
      - MYSQL_ROOT_PASSWORD=sparkos_root_pass
    ports:
      - "3306:3306"
    volumes:
      - ./base.sql:/docker-entrypoint-initdb.d/base.sql
      - sparkos_db_data:/var/lib/mysql

volumes:
  sparkos_db_data:
