<div class="nav-scroller box-shadow mb-4"><div class="container"><nav class="nav nav-underline"><a class="nav-link" href="<?= base_url(); ?>app/home"><i class="fas fa-home"></i> Dashboard</a><a class="nav-link active" href="<?= base_url(); ?>sla/lista"><i class="fas fa-file-contract"></i> SLA</a></nav></div></div>
<div role="main" class="container-fluid px-md-5">
<?php $this->load->view('layout/notifications', ['notify_view' => 'riscos', 'msg' => $msg]); ?>
<div class="my-3 p-4 rounded box-shadow"><div class="row align-items-center"><div class="col-md-6"><h5 class="card-title mb-1"><i class="fas fa-file-contract mr-2 text-primary"></i> <b>Acordos de Nível de Serviço (SLA)</b></h5></div><div class="col-md-6 text-md-right mt-3 mt-md-0"><button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#modalAdd"><i class="fas fa-plus mr-1"></i> Novo SLA</button></div></div></div>
<div class="p-4 rounded box-shadow" style="background: white;">
<div class="table-responsive">
<table class="table table-hover" id="tbl_sla"><thead><tr><th>Título</th><th>Tipo</th><th>Prioridade</th><th>Resposta</th><th>Resolução</th><th>Horário</th><th>Cliente</th><th>Status</th><th class="text-right">Ações</th></tr></thead>
<tbody><?php foreach ($slas as $s): ?><tr><td><span class="font-weight-bold" style="font-size: 13px;"><?= $s->titulo; ?></span></td><td><span class="badge badge-pill badge-<?= $s->tipo == 'INTERNO' ? 'info' : 'warning'; ?>"><?= $s->tipo; ?></span></td><td><span class="badge badge-pill badge-<?= $s->prioridade == 'CRITICA' ? 'danger' : ($s->prioridade == 'ALTA' ? 'warning' : ($s->prioridade == 'MEDIA' ? 'info' : 'secondary')); ?>"><?= $s->prioridade; ?></span></td><td class="font-weight-bold"><?= $s->tempo_resposta_h; ?>h</td><td class="font-weight-bold"><?= $s->tempo_resolucao_h; ?>h</td><td style="font-size: 11px;"><?= $s->horario_funcionamento ?: '-'; ?></td><td style="font-size: 12px;"><?= $s->cliente_nome ?: 'Geral'; ?></td><td><span class="badge badge-pill badge-<?= $s->status == 'ATIVO' ? 'success' : 'secondary'; ?>"><?= $s->status; ?></span></td><td class="text-right"><button class="btn btn-sm btn-primary py-1 px-2 btn-edit" data-id="<?= $s->idsla; ?>"><i class="fas fa-edit"></i></button><a href="<?= base_url(); ?>sla/delete/<?= $s->idsla; ?>" class="btn btn-sm btn-danger py-1 px-2" onclick="return confirm('Excluir?');"><i class="fas fa-trash"></i></a></td></tr><?php endforeach; ?></tbody></table></div></div></div>

<div class="modal fade" id="modalAdd" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title"><i class="fas fa-file-contract mr-2 text-primary"></i> Novo SLA</h5><button type="button" class="close" data-dismiss="modal"><span>&times;</span></button></div><form method="post" action="<?= base_url(); ?>sla/adicionar"><div class="modal-body p-4">
<div class="row"><div class="col-md-8"><div class="form-group"><label>Título</label><input type="text" class="form-control" name="titulo" required></div></div><div class="col-md-4"><div class="form-group"><label>Cliente</label><select class="form-control" name="cliente_id"><option value="">Geral (todos)</option><?php foreach ($clientes as $c): ?><option value="<?= $c->clientesid; ?>"><?= $c->nome; ?></option><?php endforeach; ?></select></div></div></div>
<div class="form-group"><label>Descrição</label><textarea class="form-control" name="descricao" rows="2"></textarea></div>
<div class="row"><div class="col-md-3"><div class="form-group"><label>Tipo</label><select class="form-control" name="tipo"><option value="INTERNO">Interno</option><option value="EXTERNO">Externo</option></select></div></div><div class="col-md-3"><div class="form-group"><label>Prioridade</label><select class="form-control" name="prioridade"><option value="BAIXA">Baixa</option><option value="MEDIA">Média</option><option value="ALTA">Alta</option><option value="CRITICA">Crítica</option></select></div></div><div class="col-md-3"><div class="form-group"><label>Resposta (h)</label><input type="number" step="0.1" class="form-control" name="tempo_resposta_h" value="4"></div></div><div class="col-md-3"><div class="form-group"><label>Resolução (h)</label><input type="number" step="0.1" class="form-control" name="tempo_resolucao_h" value="24"></div></div></div>
<div class="form-group"><label>Horário de Funcionamento</label><input type="text" class="form-control" name="horario_funcionamento" placeholder="08:00-18:00 Seg-Sex"></div>
<div class="form-group"><label>Penalidades</label><textarea class="form-control" name="penalidades" rows="2"></textarea></div>
</div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button><button type="submit" class="btn btn-primary">Salvar</button></div></form></div></div></div>

<div class="modal fade" id="modalEdit" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title"><i class="fas fa-edit mr-2 text-primary"></i> Editar SLA</h5><button type="button" class="close" data-dismiss="modal"><span>&times;</span></button></div><form method="post" action="<?= base_url(); ?>sla/update"><input type="hidden" name="idsla" id="edit_id"><div class="modal-body p-4">
<div class="row"><div class="col-md-8"><div class="form-group"><label>Título</label><input type="text" class="form-control" name="titulo" id="edit_titulo" required></div></div><div class="col-md-4"><div class="form-group"><label>Cliente</label><select class="form-control" name="cliente_id" id="edit_cliente_id"><option value="">Geral</option><?php foreach ($clientes as $c): ?><option value="<?= $c->clientesid; ?>"><?= $c->nome; ?></option><?php endforeach; ?></select></div></div></div>
<div class="form-group"><label>Descrição</label><textarea class="form-control" name="descricao" id="edit_descricao" rows="2"></textarea></div>
<div class="row"><div class="col-md-3"><div class="form-group"><label>Tipo</label><select class="form-control" name="tipo" id="edit_tipo"><option value="INTERNO">Interno</option><option value="EXTERNO">Externo</option></select></div></div><div class="col-md-3"><div class="form-group"><label>Prioridade</label><select class="form-control" name="prioridade" id="edit_prioridade"><option value="BAIXA">Baixa</option><option value="MEDIA">Média</option><option value="ALTA">Alta</option><option value="CRITICA">Crítica</option></select></div></div><div class="col-md-3"><div class="form-group"><label>Resposta (h)</label><input type="number" step="0.1" class="form-control" name="tempo_resposta_h" id="edit_tempo_resposta_h"></div></div><div class="col-md-3"><div class="form-group"><label>Resolução (h)</label><input type="number" step="0.1" class="form-control" name="tempo_resolucao_h" id="edit_tempo_resolucao_h"></div></div></div>
<div class="form-group"><label>Horário</label><input type="text" class="form-control" name="horario_funcionamento" id="edit_horario_funcionamento"></div>
<div class="form-group"><label>Penalidades</label><textarea class="form-control" name="penalidades" id="edit_penalidades" rows="2"></textarea></div>
</div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button><button type="submit" class="btn btn-primary">Atualizar</button></div></form></div></div></div>

<script>
$(document).ready(function() {
    if (!$.fn.DataTable.isDataTable('#tbl_sla')) $('#tbl_sla').DataTable({ "info": true, "searching": true, "paging": true, "pageLength": 10, "language": { "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Portuguese.json" } });
    $('.btn-edit').on('click', function() {
        var id = $(this).data('id');
        $.getJSON('<?= base_url(); ?>sla/get/' + id, function(data) {
            $('#edit_id').val(data.idsla); $('#edit_titulo').val(data.titulo); $('#edit_cliente_id').val(data.cliente_id);
            $('#edit_descricao').val(data.descricao); $('#edit_tipo').val(data.tipo); $('#edit_prioridade').val(data.prioridade);
            $('#edit_tempo_resposta_h').val(data.tempo_resposta_h); $('#edit_tempo_resolucao_h').val(data.tempo_resolucao_h);
            $('#edit_horario_funcionamento').val(data.horario_funcionamento); $('#edit_penalidades').val(data.penalidades);
            $('#modalEdit').modal('show');
        });
    });
});
</script>
