<div class="nav-scroller box-shadow mb-4"><div class="container"><nav class="nav nav-underline"><a class="nav-link" href="<?= base_url(); ?>app/home"><i class="fas fa-home"></i> Dashboard</a><a class="nav-link" href="<?= base_url(); ?>nfse/lista"><i class="fas fa-file-invoice-dollar"></i> NFS-e</a><a class="nav-link active" href="<?= base_url(); ?>retencoes/lista"><i class="fas fa-percent"></i> Retenções</a></nav></div></div>
<div role="main" class="container-fluid px-md-5">
<?php $this->load->view('layout/notifications', ['notify_view' => 'riscos', 'msg' => $msg]); ?>
<div class="my-3 p-4 rounded box-shadow"><div class="row align-items-center"><div class="col-md-6"><h5 class="card-title mb-1"><i class="fas fa-percent mr-2 text-primary"></i> <b>Retenções Tributárias</b></h5><p class="text-muted mb-0" style="font-size: 13px;">PIS, COFINS, CSLL, IRRF, ISS retidos na fonte.</p></div><div class="col-md-6 text-md-right mt-3 mt-md-0"><button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#modalAdd"><i class="fas fa-plus mr-1"></i> Nova Retenção</button></div></div></div>
<div class="row mb-4"><div class="col-md-12"><div class="p-3 rounded box-shadow" style="background: white;"><span class="text-muted d-block" style="font-size: 10px;">TOTAL A RECOLHER</span><h3 class="font-weight-bold mb-0" style="color: #dc2626;">R$ <?= number_format($total_reter, 2, ',', '.'); ?></h3></div></div></div>
<div class="p-4 rounded box-shadow" style="background: white;">
<table class="table table-hover" id="tbl_retencoes"><thead><tr><th>Tipo</th><th>Cliente</th><th>Valor Base</th><th>Alíquota</th><th>Valor Retenção</th><th>Data</th><th>Status</th><th class="text-right">Ações</th></tr></thead>
<tbody><?php foreach ($retencoes as $r): ?><tr><td><span class="badge badge-pill badge-info"><?= $r->tipo; ?></span></td><td style="font-size: 12px;"><?= $r->cliente_nome ?: '-'; ?></td><td>R$ <?= number_format($r->valor_base, 2, ',', '.'); ?></td><td><?= number_format($r->aliquota, 2); ?>%</td><td class="font-weight-bold" style="color: #dc2626;">R$ <?= number_format($r->valor_retencao, 2, ',', '.'); ?></td><td style="font-size: 11px;"><?= $r->data_retencao ? date('d/m/Y', strtotime($r->data_retencao)) : '-'; ?></td><td><span class="badge badge-pill badge-<?= $r->status == 'RECOLHIDO' ? 'success' : 'warning'; ?>"><?= $r->status; ?></span></td><td class="text-right"><button class="btn btn-sm btn-primary py-1 px-2 btn-edit" data-id="<?= $r->idretencao; ?>"><i class="fas fa-edit"></i></button><a href="<?= base_url(); ?>retencoes/delete/<?= $r->idretencao; ?>" class="btn btn-sm btn-danger py-1 px-2" onclick="return confirm('Excluir?');"><i class="fas fa-trash"></i></a></td></tr><?php endforeach; ?></tbody></table></div></div>

<div class="modal fade" id="modalAdd" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Nova Retenção</h5><button type="button" class="close" data-dismiss="modal"><span>&times;</span></button></div><form method="post" action="<?= base_url(); ?>retencoes/adicionar"><div class="modal-body p-3">
<div class="row"><div class="col-md-6"><div class="form-group"><label>Tipo</label><select class="form-control" name="tipo"><option value="PIS">PIS</option><option value="COFINS">COFINS</option><option value="CSLL">CSLL</option><option value="IRRF">IRRF</option><option value="ISS">ISS</option></select></div></div><div class="col-md-6"><div class="form-group"><label>Cliente</label><select class="form-control" name="clientesid"><option value="">Selecione</option><?php foreach ($clientes as $cl): ?><option value="<?= $cl->clientesid; ?>"><?= $cl->nome; ?></option><?php endforeach; ?></select></div></div></div>
<div class="row"><div class="col-md-4"><div class="form-group"><label>Valor Base (R$)</label><input type="number" step="0.01" class="form-control" name="valor_base" required></div></div><div class="col-md-4"><div class="form-group"><label>Alíquota (%)</label><input type="number" step="0.01" class="form-control" name="aliquota"></div></div><div class="col-md-4"><div class="form-group"><label>Valor Retenção</label><input type="number" step="0.01" class="form-control" name="valor_retencao" required></div></div></div>
<div class="row"><div class="col-md-6"><div class="form-group"><label>Data</label><input type="date" class="form-control" name="data_retencao" value="<?= date('Y-m-d'); ?>"></div></div><div class="col-md-6"><div class="form-group"><label>Status</label><select class="form-control" name="status"><option value="PENDENTE">Pendente</option><option value="RECOLHIDO">Recolhido</option></select></div></div></div>
</div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button><button type="submit" class="btn btn-primary">Salvar</button></div></form></div></div></div>

<div class="modal fade" id="modalEdit" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Editar Retenção</h5><button type="button" class="close" data-dismiss="modal"><span>&times;</span></button></div><form method="post" action="<?= base_url(); ?>retencoes/update"><input type="hidden" name="idretencao" id="edit_id"><div class="modal-body p-3">
<div class="row"><div class="col-md-6"><div class="form-group"><label>Tipo</label><select class="form-control" name="tipo" id="edit_tipo"><option value="PIS">PIS</option><option value="COFINS">COFINS</option><option value="CSLL">CSLL</option><option value="IRRF">IRRF</option><option value="ISS">ISS</option></select></div></div><div class="col-md-6"><div class="form-group"><label>Cliente</label><select class="form-control" name="clientesid" id="edit_clientesid"><?php foreach ($clientes as $cl): ?><option value="<?= $cl->clientesid; ?>"><?= $cl->nome; ?></option><?php endforeach; ?></select></div></div></div>
<div class="row"><div class="col-md-4"><div class="form-group"><label>Valor Base</label><input type="number" step="0.01" class="form-control" name="valor_base" id="edit_valor_base"></div></div><div class="col-md-4"><div class="form-group"><label>Alíquota</label><input type="number" step="0.01" class="form-control" name="aliquota" id="edit_aliquota"></div></div><div class="col-md-4"><div class="form-group"><label>Valor Retenção</label><input type="number" step="0.01" class="form-control" name="valor_retencao" id="edit_valor_retencao"></div></div></div>
<div class="row"><div class="col-md-6"><div class="form-group"><label>Data</label><input type="date" class="form-control" name="data_retencao" id="edit_data_retencao"></div></div><div class="col-md-6"><div class="form-group"><label>Status</label><select class="form-control" name="status" id="edit_status"><option value="PENDENTE">Pendente</option><option value="RECOLHIDO">Recolhido</option></select></div></div></div>
</div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button><button type="submit" class="btn btn-primary">Atualizar</button></div></form></div></div></div>

<script>
$(document).ready(function() {
    if (!$.fn.DataTable.isDataTable('#tbl_retencoes')) $('#tbl_retencoes').DataTable({ "info": true, "searching": true, "paging": true, "pageLength": 15, "order": [[5, 'desc']], "language": { "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Portuguese.json" } });
    $('.btn-edit').on('click', function() {
        $.getJSON('<?= base_url(); ?>retencoes/get/' + $(this).data('id'), function(data) {
            $('#edit_id').val(data.idretencao); $('#edit_tipo').val(data.tipo); $('#edit_clientesid').val(data.clientesid);
            $('#edit_valor_base').val(data.valor_base); $('#edit_aliquota').val(data.aliquota); $('#edit_valor_retencao').val(data.valor_retencao);
            if (data.data_retencao) $('#edit_data_retencao').val(data.data_retencao);
            $('#edit_status').val(data.status);
            $('#modalEdit').modal('show');
        });
    });
});
</script>
