<div class="nav-scroller box-shadow mb-4"><div class="container"><nav class="nav nav-underline"><a class="nav-link" href="<?= base_url(); ?>app/home"><i class="fas fa-home"></i> Dashboard</a><a class="nav-link active" href="<?= base_url(); ?>custos/lista"><i class="fas fa-coins"></i> Custos</a></nav></div></div>
<div role="main" class="container-fluid px-md-5">
<?php $this->load->view('layout/notifications', ['notify_view' => 'riscos', 'msg' => $msg]); ?>
<div class="my-3 p-4 rounded box-shadow"><div class="row align-items-center"><div class="col-md-6"><h5 class="card-title mb-1"><i class="fas fa-coins mr-2 text-primary"></i> <b>Custos e Despesas</b></h5><p class="text-muted mb-0" style="font-size: 13px;">Registro de custos operacionais e administrativos.</p></div><div class="col-md-6 text-md-right mt-3 mt-md-0"><button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#modalAdd"><i class="fas fa-plus mr-1"></i> Novo Custo</button></div></div></div>
<div class="row mb-4"><div class="col-md-12"><div class="p-3 rounded box-shadow" style="background: white;"><span class="text-muted d-block" style="font-size: 10px;">CUSTOS DO MÊS</span><h3 class="font-weight-bold mb-0" style="color: #ef4444;">R$ <?= number_format($total_mes, 2, ',', '.'); ?></h3></div></div></div>
<div class="p-4 rounded box-shadow" style="background: white;">
<div class="table-responsive">
<table class="table table-hover" id="tbl_custos"><thead><tr><th>Descrição</th><th>Categoria</th><th>Tipo</th><th>Valor</th><th>Data</th><th>Fornecedor</th><th>Pagamento</th><th>Status</th><th class="text-right">Ações</th></tr></thead>
<tbody><?php foreach ($custos as $c): ?><tr><td><span class="font-weight-bold" style="font-size: 13px;"><?= $c->descricao; ?></span></td><td style="font-size: 12px;"><?= $c->categoria_nome ?: '-'; ?></td><td><span class="badge badge-pill badge-<?= $c->tipo == 'FIXO' ? 'info' : 'warning'; ?>"><?= $c->tipo; ?></span></td><td class="font-weight-bold" style="color: #dc2626;">R$ <?= number_format($c->valor, 2, ',', '.'); ?></td><td style="font-size: 11px;"><?= $c->data_ocorrencia ? date('d/m/Y', strtotime($c->data_ocorrencia)) : '-'; ?></td><td style="font-size: 12px;"><?= $c->fornecedor ?: '-'; ?></td><td style="font-size: 11px;"><?= $c->forma_pagamento; ?></td><td><span class="badge badge-pill badge-<?= $c->status == 'PAGO' ? 'success' : 'warning'; ?>"><?= $c->status; ?></span></td><td class="text-right"><button class="btn btn-sm btn-primary py-1 px-2 btn-edit" data-id="<?= $c->idcusto; ?>"><i class="fas fa-edit"></i></button><a href="<?= base_url(); ?>custos/delete/<?= $c->idcusto; ?>" class="btn btn-sm btn-danger py-1 px-2" onclick="return confirm('Excluir?');"><i class="fas fa-trash"></i></a></td></tr><?php endforeach; ?></tbody></table></div></div></div>

<div class="modal fade" id="modalAdd" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title"><i class="fas fa-coins mr-2 text-primary"></i> Novo Custo</h5><button type="button" class="close" data-dismiss="modal"><span>&times;</span></button></div><form method="post" action="<?= base_url(); ?>custos/adicionar"><div class="modal-body p-4">
<div class="form-group"><label>Descrição</label><input type="text" class="form-control" name="descricao" required></div>
<div class="row"><div class="col-md-6"><div class="form-group"><label>Categoria</label><select class="form-control" name="idcategoria"><option value="">Selecione</option><?php foreach ($categorias as $cat): ?><option value="<?= $cat->idcategoria; ?>"><?= $cat->nome; ?></option><?php endforeach; ?></select></div></div><div class="col-md-3"><div class="form-group"><label>Tipo</label><select class="form-control" name="tipo"><option value="VARIAVEL">Variável</option><option value="FIXO">Fixo</option></select></div></div><div class="col-md-3"><div class="form-group"><label>Valor (R$)</label><input type="number" step="0.01" class="form-control" name="valor" required></div></div></div>
<div class="row"><div class="col-md-6"><div class="form-group"><label>Data</label><input type="date" class="form-control" name="data_ocorrencia" value="<?= date('Y-m-d'); ?>"></div></div><div class="col-md-6"><div class="form-group"><label>Fornecedor</label><input type="text" class="form-control" name="fornecedor"></div></div></div>
<div class="row"><div class="col-md-6"><div class="form-group"><label>Forma Pagamento</label><select class="form-control" name="forma_pagamento"><option value="DINHEIRO">Dinheiro</option><option value="PIX">Pix</option><option value="CARTAO">Cartão</option><option value="BOLETO">Boleto</option><option value="TRANSFERENCIA">Transferência</option></select></div></div><div class="col-md-6"><div class="form-group"><label>Status</label><select class="form-control" name="status"><option value="PAGO">Pago</option><option value="PENDENTE">Pendente</option></select></div></div></div>
<div class="form-group"><label>Observações</label><textarea class="form-control" name="observacoes" rows="2"></textarea></div>
</div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button><button type="submit" class="btn btn-primary">Salvar</button></div></form></div></div></div>

<div class="modal fade" id="modalEdit" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title"><i class="fas fa-edit mr-2 text-primary"></i> Editar Custo</h5><button type="button" class="close" data-dismiss="modal"><span>&times;</span></button></div><form method="post" action="<?= base_url(); ?>custos/update"><input type="hidden" name="idcusto" id="edit_id"><div class="modal-body p-4">
<div class="form-group"><label>Descrição</label><input type="text" class="form-control" name="descricao" id="edit_descricao" required></div>
<div class="row"><div class="col-md-6"><div class="form-group"><label>Categoria</label><select class="form-control" name="idcategoria" id="edit_idcategoria"><option value="">Selecione</option><?php foreach ($categorias as $cat): ?><option value="<?= $cat->idcategoria; ?>"><?= $cat->nome; ?></option><?php endforeach; ?></select></div></div><div class="col-md-3"><div class="form-group"><label>Tipo</label><select class="form-control" name="tipo" id="edit_tipo"><option value="VARIAVEL">Variável</option><option value="FIXO">Fixo</option></select></div></div><div class="col-md-3"><div class="form-group"><label>Valor</label><input type="number" step="0.01" class="form-control" name="valor" id="edit_valor" required></div></div></div>
<div class="row"><div class="col-md-6"><div class="form-group"><label>Data</label><input type="date" class="form-control" name="data_ocorrencia" id="edit_data_ocorrencia"></div></div><div class="col-md-6"><div class="form-group"><label>Fornecedor</label><input type="text" class="form-control" name="fornecedor" id="edit_fornecedor"></div></div></div>
<div class="row"><div class="col-md-6"><div class="form-group"><label>Pagamento</label><select class="form-control" name="forma_pagamento" id="edit_forma_pagamento"><option value="DINHEIRO">Dinheiro</option><option value="PIX">Pix</option></select></div></div><div class="col-md-6"><div class="form-group"><label>Status</label><select class="form-control" name="status" id="edit_status"><option value="PAGO">Pago</option><option value="PENDENTE">Pendente</option></select></div></div></div>
<div class="form-group"><label>Observações</label><textarea class="form-control" name="observacoes" id="edit_observacoes" rows="2"></textarea></div>
</div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button><button type="submit" class="btn btn-primary">Atualizar</button></div></form></div></div></div>

<script>
$(document).ready(function() {
    if (!$.fn.DataTable.isDataTable('#tbl_custos')) $('#tbl_custos').DataTable({ "info": true, "searching": true, "paging": true, "pageLength": 15, "order": [[4, 'desc']], "language": { "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Portuguese.json" } });
    $('.btn-edit').on('click', function() {
        var id = $(this).data('id');
        $.getJSON('<?= base_url(); ?>custos/get/' + id, function(data) {
            $('#edit_id').val(data.idcusto); $('#edit_descricao').val(data.descricao);
            $('#edit_idcategoria').val(data.idcategoria); $('#edit_tipo').val(data.tipo);
            $('#edit_valor').val(data.valor); $('#edit_fornecedor').val(data.fornecedor);
            $('#edit_forma_pagamento').val(data.forma_pagamento); $('#edit_status').val(data.status);
            if (data.data_ocorrencia) $('#edit_data_ocorrencia').val(data.data_ocorrencia);
            $('#edit_observacoes').val(data.observacoes);
            $('#modalEdit').modal('show');
        });
    });
});
</script>
