<div class="nav-scroller box-shadow mb-4"><div class="container"><nav class="nav nav-underline"><a class="nav-link" href="<?= base_url(); ?>app/home"><i class="fas fa-home"></i> Dashboard</a><a class="nav-link active" href="<?= base_url(); ?>equipamentos/lista"><i class="fas fa-server"></i> Equipamentos</a></nav></div></div>
<div role="main" class="container-fluid px-md-5">
<?php $this->load->view('layout/notifications', ['notify_view' => 'riscos', 'msg' => $msg]); ?>
<div class="my-3 p-4 rounded box-shadow"><div class="row align-items-center"><div class="col-md-6"><h5 class="card-title mb-1"><i class="fas fa-server mr-2 text-primary"></i> <b>Equipamentos</b></h5><p class="text-muted mb-0" style="font-size: 13px;">Registro de equipamentos dos clientes.</p></div><div class="col-md-6 text-md-right mt-3 mt-md-0"><button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#modalAdd"><i class="fas fa-plus mr-1"></i> Novo Equipamento</button></div></div></div>
<div class="p-4 rounded box-shadow" style="background: white;">
<div class="table-responsive">
<table class="table table-hover" id="tbl_equipamentos">
<thead><tr><th>Patrimônio</th><th>Equipamento</th><th>Categoria</th><th>Marca</th><th>Modelo</th><th>Nº Série</th><th>Cliente</th><th>Garantia</th><th>Status</th><th class="text-right">Ações</th></tr></thead>
<tbody><?php foreach ($equipamentos as $e): ?><tr><td><span class="font-weight-bold" style="font-size: 12px;"><?= $e->patrimonio ?: '-'; ?></span></td><td><span class="font-weight-bold" style="font-size: 13px;"><?= $e->tipo ?: 'Equipamento'; ?></span></td><td><span class="badge badge-pill badge-info" style="font-size: 9px;"><?= $e->categoria_nome ?: '-'; ?></span></td><td style="font-size: 12px;"><?= $e->marca ?: '-'; ?></td><td style="font-size: 12px;"><?= $e->modelo ?: '-'; ?></td><td style="font-size: 11px;"><?= $e->numero_serie ?: '-'; ?></td><td style="font-size: 12px;"><?= $e->cliente_nome ?: '-'; ?></td><td style="font-size: 11px;"><?= $e->data_garantia ? date('d/m/Y', strtotime($e->data_garantia)) : '-'; ?></td><td><span class="badge badge-pill badge-<?= $e->status == 'ATIVO' ? 'success' : ($e->status == 'EM_MANUTENCAO' ? 'warning' : 'secondary'); ?>"><?= $e->status; ?></span></td><td class="text-right"><button class="btn btn-sm btn-primary py-1 px-2 btn-edit" data-id="<?= $e->idequipamento; ?>" style="font-size: 11px;"><i class="fas fa-edit"></i></button><a href="<?= base_url(); ?>equipamentos/delete/<?= $e->idequipamento; ?>" class="btn btn-sm btn-danger py-1 px-2" style="font-size: 11px;" onclick="return confirm('Excluir?');"><i class="fas fa-trash"></i></a></td></tr><?php endforeach; ?></tbody></table></div></div></div>

<div class="modal fade" id="modalAdd" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title"><i class="fas fa-server mr-2 text-primary"></i> Novo Equipamento</h5><button type="button" class="close" data-dismiss="modal"><span>&times;</span></button></div><form method="post" action="<?= base_url(); ?>equipamentos/adicionar"><div class="modal-body p-4">
<div class="row"><div class="col-md-6"><div class="form-group"><label>Cliente</label><select class="form-control" name="clientesid"><option value="">Selecione</option><?php foreach ($clientes as $c): ?><option value="<?= $c->clientesid; ?>"><?= $c->nome; ?></option><?php endforeach; ?></select></div></div><div class="col-md-3"><div class="form-group"><label>Categoria</label><select class="form-control" name="idcategoria"><option value="">Selecione</option><?php foreach ($categorias as $cat): ?><option value="<?= $cat->idcategoria; ?>"><?= $cat->nome; ?></option><?php endforeach; ?></select></div></div><div class="col-md-3"><div class="form-group"><label>Tipo</label><input type="text" class="form-control" name="tipo" placeholder="Ex: Servidor"></div></div></div>
<div class="row"><div class="col-md-4"><div class="form-group"><label>Marca</label><input type="text" class="form-control" name="marca"></div></div><div class="col-md-4"><div class="form-group"><label>Modelo</label><input type="text" class="form-control" name="modelo"></div></div><div class="col-md-4"><div class="form-group"><label>Nº Série</label><input type="text" class="form-control" name="numero_serie"></div></div></div>
<div class="row"><div class="col-md-4"><div class="form-group"><label>Patrimônio</label><input type="text" class="form-control" name="patrimonio"></div></div><div class="col-md-4"><div class="form-group"><label>Data Instalação</label><input type="date" class="form-control" name="data_instalacao"></div></div><div class="col-md-4"><div class="form-group"><label>Garantia até</label><input type="date" class="form-control" name="data_garantia"></div></div></div>
<div class="row"><div class="col-md-6"><div class="form-group"><label>Status</label><select class="form-control" name="status"><option value="ATIVO">Ativo</option><option value="EM_MANUTENCAO">Em Manutenção</option><option value="INATIVO">Inativo</option></select></div></div></div>
<div class="form-group"><label>Especificações</label><textarea class="form-control" name="especificacoes" rows="2"></textarea></div>
<div class="form-group"><label>Observações</label><textarea class="form-control" name="observacoes" rows="2"></textarea></div>
</div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button><button type="submit" class="btn btn-primary">Salvar</button></div></form></div></div></div>

<div class="modal fade" id="modalEdit" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title"><i class="fas fa-edit mr-2 text-primary"></i> Editar Equipamento</h5><button type="button" class="close" data-dismiss="modal"><span>&times;</span></button></div><form method="post" action="<?= base_url(); ?>equipamentos/update"><input type="hidden" name="idequipamento" id="edit_id"><div class="modal-body p-4">
<div class="row"><div class="col-md-6"><div class="form-group"><label>Cliente</label><select class="form-control" name="clientesid" id="edit_clientesid"><option value="">Selecione</option><?php foreach ($clientes as $c): ?><option value="<?= $c->clientesid; ?>"><?= $c->nome; ?></option><?php endforeach; ?></select></div></div><div class="col-md-3"><div class="form-group"><label>Categoria</label><select class="form-control" name="idcategoria" id="edit_idcategoria"><option value="">Selecione</option><?php foreach ($categorias as $cat): ?><option value="<?= $cat->idcategoria; ?>"><?= $cat->nome; ?></option><?php endforeach; ?></select></div></div><div class="col-md-3"><div class="form-group"><label>Tipo</label><input type="text" class="form-control" name="tipo" id="edit_tipo"></div></div></div>
<div class="row"><div class="col-md-4"><div class="form-group"><label>Marca</label><input type="text" class="form-control" name="marca" id="edit_marca"></div></div><div class="col-md-4"><div class="form-group"><label>Modelo</label><input type="text" class="form-control" name="modelo" id="edit_modelo"></div></div><div class="col-md-4"><div class="form-group"><label>Nº Série</label><input type="text" class="form-control" name="numero_serie" id="edit_numero_serie"></div></div></div>
<div class="row"><div class="col-md-4"><div class="form-group"><label>Patrimônio</label><input type="text" class="form-control" name="patrimonio" id="edit_patrimonio"></div></div><div class="col-md-4"><div class="form-group"><label>Instalação</label><input type="date" class="form-control" name="data_instalacao" id="edit_data_instalacao"></div></div><div class="col-md-4"><div class="form-group"><label>Garantia</label><input type="date" class="form-control" name="data_garantia" id="edit_data_garantia"></div></div></div>
<div class="form-group"><label>Especificações</label><textarea class="form-control" name="especificacoes" id="edit_especificacoes" rows="2"></textarea></div>
<div class="form-group"><label>Observações</label><textarea class="form-control" name="observacoes" id="edit_observacoes" rows="2"></textarea></div>
</div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button><button type="submit" class="btn btn-primary">Atualizar</button></div></form></div></div></div>

<script>
$(document).ready(function() {
    if (!$.fn.DataTable.isDataTable('#tbl_equipamentos')) $('#tbl_equipamentos').DataTable({ "info": true, "searching": true, "paging": true, "pageLength": 15, "language": { "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Portuguese.json" } });
    $('.btn-edit').on('click', function() {
        var id = $(this).data('id');
        $.getJSON('<?= base_url(); ?>equipamentos/get/' + id, function(data) {
            $('#edit_id').val(data.idequipamento); $('#edit_clientesid').val(data.clientesid); $('#edit_idcategoria').val(data.idcategoria);
            $('#edit_tipo').val(data.tipo); $('#edit_marca').val(data.marca); $('#edit_modelo').val(data.modelo);
            $('#edit_numero_serie').val(data.numero_serie); $('#edit_patrimonio').val(data.patrimonio);
            if (data.data_instalacao) $('#edit_data_instalacao').val(data.data_instalacao);
            if (data.data_garantia) $('#edit_data_garantia').val(data.data_garantia);
            $('#edit_especificacoes').val(data.especificacoes); $('#edit_observacoes').val(data.observacoes);
            $('#modalEdit').modal('show');
        });
    });
});
</script>
