<div class="nav-scroller box-shadow mb-4"><div class="container"><nav class="nav nav-underline"><a class="nav-link" href="<?= base_url(); ?>app/home"><i class="fas fa-home"></i> Dashboard</a><a class="nav-link active" href="<?= base_url(); ?>conciliacao/lista"><i class="fas fa-exchange-alt"></i> Conciliação</a></nav></div></div>
<div role="main" class="container-fluid px-md-5">
<?php $this->load->view('layout/notifications', ['notify_view' => 'riscos', 'msg' => $msg]); ?>
<div class="my-3 p-4 rounded box-shadow"><div class="row align-items-center"><div class="col-md-6"><h5 class="card-title mb-1"><i class="fas fa-exchange-alt mr-2 text-primary"></i> <b>Conciliação Bancária</b></h5><p class="text-muted mb-0" style="font-size: 13px;">Conciliação de lançamentos financeiros.</p></div><div class="col-md-6 text-md-right mt-3 mt-md-0"><button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#modalAdd"><i class="fas fa-plus mr-1"></i> Novo Lançamento</button></div></div></div>
<div class="row mb-4"><div class="col-md-6"><div class="p-3 rounded box-shadow" style="background: white;"><span class="text-muted d-block" style="font-size: 10px;">PENDENTE CONCILIAÇÃO</span><h3 class="font-weight-bold mb-0" style="color: #f59e0b;">R$ <?= number_format($total_pendente, 2, ',', '.'); ?></h3></div></div><div class="col-md-6"><div class="p-3 rounded box-shadow" style="background: white;"><span class="text-muted d-block" style="font-size: 10px;">CONCILIADO</span><h3 class="font-weight-bold mb-0" style="color: #059669;">R$ <?= number_format($total_conciliado, 2, ',', '.'); ?></h3></div></div></div>
<div class="p-4 rounded box-shadow" style="background: white;">
<table class="table table-hover" id="tbl_conciliacao"><thead><tr><th>Descrição</th><th>Tipo</th><th>Categoria</th><th>Valor</th><th>Data</th><th>Conta</th><th>Status</th><th class="text-right">Ações</th></tr></thead>
<tbody><?php foreach ($lancamentos as $l): ?><tr><td><span class="font-weight-bold" style="font-size: 13px;"><?= $l->descricao; ?></span></td><td><span class="badge badge-pill badge-<?= $l->tipo == 'RECEITA' ? 'success' : 'danger'; ?>"><?= $l->tipo; ?></span></td><td style="font-size: 12px;"><?= $l->categoria ?: '-'; ?></td><td class="font-weight-bold" style="color: <?= $l->tipo == 'RECEITA' ? '#059669' : '#dc2626'; ?>;">R$ <?= number_format($l->valor, 2, ',', '.'); ?></td><td style="font-size: 11px;"><?= $l->data_lancamento ? date('d/m/Y', strtotime($l->data_lancamento)) : '-'; ?></td><td style="font-size: 12px;"><?= $l->conta_bancaria ?: '-'; ?></td><td><span class="badge badge-pill badge-<?= $l->status == 'CONCILIADO' ? 'success' : 'warning'; ?>"><?= $l->status; ?></span></td><td class="text-right"><?php if ($l->status != 'CONCILIADO'): ?><a href="<?= base_url(); ?>conciliacao/conciliar/<?= $l->idlancamento; ?>" class="btn btn-sm btn-success py-1 px-2" title="Conciliar" onclick="return confirm('Confirmar conciliação?');"><i class="fas fa-check"></i></a><?php endif; ?><button class="btn btn-sm btn-primary py-1 px-2 btn-edit" data-id="<?= $l->idlancamento; ?>"><i class="fas fa-edit"></i></button><a href="<?= base_url(); ?>conciliacao/delete/<?= $l->idlancamento; ?>" class="btn btn-sm btn-danger py-1 px-2" onclick="return confirm('Excluir?');"><i class="fas fa-trash"></i></a></td></tr><?php endforeach; ?></tbody></table></div></div>

<div class="modal fade" id="modalAdd" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title"><i class="fas fa-plus mr-2 text-primary"></i> Novo Lançamento</h5><button type="button" class="close" data-dismiss="modal"><span>&times;</span></button></div><form method="post" action="<?= base_url(); ?>conciliacao/adicionar"><div class="modal-body p-3">
<div class="form-group"><label>Descrição</label><input type="text" class="form-control" name="descricao" required></div>
<div class="row"><div class="col-md-6"><div class="form-group"><label>Tipo</label><select class="form-control" name="tipo"><option value="RECEITA">Receita</option><option value="DESPESA">Despesa</option></select></div></div><div class="col-md-6"><div class="form-group"><label>Categoria</label><input type="text" class="form-control" name="categoria"></div></div></div>
<div class="row"><div class="col-md-4"><div class="form-group"><label>Valor (R$)</label><input type="number" step="0.01" class="form-control" name="valor" required></div></div><div class="col-md-4"><div class="form-group"><label>Data</label><input type="date" class="form-control" name="data_lancamento" value="<?= date('Y-m-d'); ?>"></div></div><div class="col-md-4"><div class="form-group"><label>Conta</label><input type="text" class="form-control" name="conta_bancaria" placeholder="Ex: Itaú - 1234"></div></div></div>
<div class="form-group"><label>Documento</label><input type="text" class="form-control" name="documento"></div>
<div class="form-group"><label>Observações</label><textarea class="form-control" name="observacoes" rows="2"></textarea></div>
</div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button><button type="submit" class="btn btn-primary">Salvar</button></div></form></div></div></div>

<div class="modal fade" id="modalEdit" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title"><i class="fas fa-edit mr-2 text-primary"></i> Editar Lançamento</h5><button type="button" class="close" data-dismiss="modal"><span>&times;</span></button></div><form method="post" action="<?= base_url(); ?>conciliacao/update"><input type="hidden" name="idlancamento" id="edit_id"><div class="modal-body p-3">
<div class="form-group"><label>Descrição</label><input type="text" class="form-control" name="descricao" id="edit_descricao" required></div>
<div class="row"><div class="col-md-6"><div class="form-group"><label>Tipo</label><select class="form-control" name="tipo" id="edit_tipo"><option value="RECEITA">Receita</option><option value="DESPESA">Despesa</option></select></div></div><div class="col-md-6"><div class="form-group"><label>Categoria</label><input type="text" class="form-control" name="categoria" id="edit_categoria"></div></div></div>
<div class="row"><div class="col-md-4"><div class="form-group"><label>Valor</label><input type="number" step="0.01" class="form-control" name="valor" id="edit_valor" required></div></div><div class="col-md-4"><div class="form-group"><label>Data</label><input type="date" class="form-control" name="data_lancamento" id="edit_data_lancamento"></div></div><div class="col-md-4"><div class="form-group"><label>Conta</label><input type="text" class="form-control" name="conta_bancaria" id="edit_conta_bancaria"></div></div></div>
<div class="form-group"><label>Documento</label><input type="text" class="form-control" name="documento" id="edit_documento"></div>
<div class="form-group"><label>Data Conciliação</label><input type="date" class="form-control" name="data_conciliacao" id="edit_data_conciliacao"></div>
<div class="form-group"><label>Status</label><select class="form-control" name="status" id="edit_status"><option value="PENDENTE">Pendente</option><option value="CONCILIADO">Conciliado</option></select></div>
<div class="form-group"><label>Observações</label><textarea class="form-control" name="observacoes" id="edit_observacoes" rows="2"></textarea></div>
</div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button><button type="submit" class="btn btn-primary">Atualizar</button></div></form></div></div></div>

<script>
$(document).ready(function() {
    if (!$.fn.DataTable.isDataTable('#tbl_conciliacao')) $('#tbl_conciliacao').DataTable({ "info": true, "searching": true, "paging": true, "pageLength": 15, "order": [[4, 'desc']], "language": { "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Portuguese.json" } });
    $('.btn-edit').on('click', function() {
        $.getJSON('<?= base_url(); ?>conciliacao/get/' + $(this).data('id'), function(data) {
            $('#edit_id').val(data.idlancamento); $('#edit_descricao').val(data.descricao);
            $('#edit_tipo').val(data.tipo); $('#edit_categoria').val(data.categoria); $('#edit_valor').val(data.valor);
            if (data.data_lancamento) $('#edit_data_lancamento').val(data.data_lancamento);
            $('#edit_conta_bancaria').val(data.conta_bancaria); $('#edit_documento').val(data.documento);
            if (data.data_conciliacao) $('#edit_data_conciliacao').val(data.data_conciliacao);
            $('#edit_status').val(data.status); $('#edit_observacoes').val(data.observacoes);
            $('#modalEdit').modal('show');
        });
    });
});
</script>
