<div class="nav-scroller box-shadow mb-4"><div class="container"><nav class="nav nav-underline"><a class="nav-link" href="<?= base_url(); ?>app/home"><i class="fas fa-home"></i> Dashboard</a><a class="nav-link" href="<?= base_url(); ?>clientes/lista"><i class="fas fa-users"></i> Clientes</a><a class="nav-link active" href="<?= base_url(); ?>cadastrofiscal/lista"><i class="fas fa-file-invoice"></i> Cadastro Fiscal</a></nav></div></div>
<div role="main" class="container-fluid px-md-5">
<?php $this->load->view('layout/notifications', ['notify_view' => 'riscos', 'msg' => $msg]); ?>
<div class="my-3 p-4 rounded box-shadow"><div class="row align-items-center"><div class="col-md-6"><h5 class="card-title mb-1"><i class="fas fa-file-invoice mr-2 text-primary"></i> <b>Cadastro Fiscal de Clientes</b></h5><p class="text-muted mb-0" style="font-size: 13px;">Regime tributário, CNAE, inscrições estaduais e municipais.</p></div><div class="col-md-6 text-md-right mt-3 mt-md-0"><button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#modalAdd"><i class="fas fa-plus mr-1"></i> Novo Cadastro</button></div></div></div>
<div class="p-4 rounded box-shadow" style="background: white;">
<table class="table table-hover" id="tbl_fiscal"><thead><tr><th>Cliente</th><th>Documento</th><th>Regime</th><th>CNAE</th><th>Insc. Estadual</th><th>Insc. Municipal</th><th>Aliq. ISS</th><th class="text-right">Ações</th></tr></thead>
<tbody><?php foreach ($cadastros as $c): ?><tr><td><span class="font-weight-bold" style="font-size: 13px;"><?= $c->cliente_nome ?: '-'; ?></span></td><td><code><?= $c->documento ?: '-'; ?></code></td><td><span class="badge badge-pill badge-<?= $c->regime_tributario == 'SIMPLES_NACIONAL' ? 'success' : ($c->regime_tributario == 'LUCRO_PRESUMIDO' ? 'info' : 'warning'); ?>" style="font-size: 9px;"><?= $c->regime_tributario ?: '-'; ?></span></td><td style="font-size: 12px;"><?= $c->cnae ?: '-'; ?></td><td style="font-size: 12px;"><?= $c->inscricao_estadual ?: '-'; ?></td><td style="font-size: 12px;"><?= $c->inscricao_municipal ?: '-'; ?></td><td class="font-weight-bold"><?= $c->aliquota_iss ? number_format($c->aliquota_iss, 2).'%' : '-'; ?></td><td class="text-right"><button class="btn btn-sm btn-primary py-1 px-2 btn-edit" data-id="<?= $c->idcadastro; ?>"><i class="fas fa-edit"></i></button><a href="<?= base_url(); ?>cadastrofiscal/delete/<?= $c->idcadastro; ?>" class="btn btn-sm btn-danger py-1 px-2" onclick="return confirm('Excluir?');"><i class="fas fa-trash"></i></a></td></tr><?php endforeach; ?></tbody></table></div></div>

<div class="modal fade" id="modalAdd" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title"><i class="fas fa-plus mr-2 text-primary"></i> Novo Cadastro Fiscal</h5><button type="button" class="close" data-dismiss="modal"><span>&times;</span></button></div><form method="post" action="<?= base_url(); ?>cadastrofiscal/adicionar"><div class="modal-body p-3">
<div class="form-group"><label>Cliente</label><select class="form-control" name="clientesid" required><option value="">Selecione</option><?php foreach ($clientes as $cl): ?><option value="<?= $cl->clientesid; ?>"><?= $cl->nome; ?> <?= $cl->documento ? '/ '.$cl->documento : ''; ?></option><?php endforeach; ?></select></div>
<div class="row"><div class="col-md-6"><div class="form-group"><label>Regime Tributário</label><select class="form-control" name="regime_tributario"><option value="SIMPLES_NACIONAL">Simples Nacional</option><option value="MEI">MEI</option><option value="LUCRO_PRESUMIDO">Lucro Presumido</option><option value="LUCRO_REAL">Lucro Real</option></select></div></div><div class="col-md-6"><div class="form-group"><label>CNAE</label><input type="text" class="form-control" name="cnae"></div></div></div>
<div class="row"><div class="col-md-6"><div class="form-group"><label>Inscrição Estadual</label><input type="text" class="form-control" name="inscricao_estadual"></div></div><div class="col-md-6"><div class="form-group"><label>Inscrição Municipal</label><input type="text" class="form-control" name="inscricao_municipal"></div></div></div>
<div class="row"><div class="col-md-6"><div class="form-group"><label>Aliq. ISS (%)</label><input type="number" step="0.01" class="form-control" name="aliquota_iss" value="0"></div></div><div class="col-md-6"><div class="form-group"><label>Aliq. ICMS (%)</label><input type="number" step="0.01" class="form-control" name="aliquota_icms" value="0"></div></div></div>
<div class="form-group"><label>Observações</label><textarea class="form-control" name="observacoes" rows="2"></textarea></div>
</div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button><button type="submit" class="btn btn-primary">Salvar</button></div></form></div></div></div>

<div class="modal fade" id="modalEdit" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title"><i class="fas fa-edit mr-2 text-primary"></i> Editar Cadastro Fiscal</h5><button type="button" class="close" data-dismiss="modal"><span>&times;</span></button></div><form method="post" action="<?= base_url(); ?>cadastrofiscal/update"><input type="hidden" name="idcadastro" id="edit_id"><div class="modal-body p-3">
<div class="form-group"><label>Cliente</label><select class="form-control" name="clientesid" id="edit_clientesid"><?php foreach ($clientes as $cl): ?><option value="<?= $cl->clientesid; ?>"><?= $cl->nome; ?></option><?php endforeach; ?></select></div>
<div class="row"><div class="col-md-6"><div class="form-group"><label>Regime</label><select class="form-control" name="regime_tributario" id="edit_regime_tributario"><option value="SIMPLES_NACIONAL">Simples Nacional</option><option value="MEI">MEI</option><option value="LUCRO_PRESUMIDO">Lucro Presumido</option><option value="LUCRO_REAL">Lucro Real</option></select></div></div><div class="col-md-6"><div class="form-group"><label>CNAE</label><input type="text" class="form-control" name="cnae" id="edit_cnae"></div></div></div>
<div class="row"><div class="col-md-6"><div class="form-group"><label>Insc. Estadual</label><input type="text" class="form-control" name="inscricao_estadual" id="edit_inscricao_estadual"></div></div><div class="col-md-6"><div class="form-group"><label>Insc. Municipal</label><input type="text" class="form-control" name="inscricao_municipal" id="edit_inscricao_municipal"></div></div></div>
<div class="row"><div class="col-md-6"><div class="form-group"><label>Aliq. ISS</label><input type="number" step="0.01" class="form-control" name="aliquota_iss" id="edit_aliquota_iss"></div></div><div class="col-md-6"><div class="form-group"><label>Aliq. ICMS</label><input type="number" step="0.01" class="form-control" name="aliquota_icms" id="edit_aliquota_icms"></div></div></div>
<div class="form-group"><label>Observações</label><textarea class="form-control" name="observacoes" id="edit_observacoes" rows="2"></textarea></div>
</div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button><button type="submit" class="btn btn-primary">Atualizar</button></div></form></div></div></div>

<script>
$(document).ready(function() {
    if (!$.fn.DataTable.isDataTable('#tbl_fiscal')) $('#tbl_fiscal').DataTable({ "info": true, "searching": true, "paging": true, "pageLength": 15, "order": [[0, 'asc']], "language": { "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Portuguese.json" } });
    $('.btn-edit').on('click', function() {
        $.getJSON('<?= base_url(); ?>cadastrofiscal/get/' + $(this).data('id'), function(data) {
            $('#edit_id').val(data.idcadastro); $('#edit_clientesid').val(data.clientesid);
            $('#edit_regime_tributario').val(data.regime_tributario); $('#edit_cnae').val(data.cnae);
            $('#edit_inscricao_estadual').val(data.inscricao_estadual); $('#edit_inscricao_municipal').val(data.inscricao_municipal);
            $('#edit_aliquota_iss').val(data.aliquota_iss); $('#edit_aliquota_icms').val(data.aliquota_icms);
            $('#edit_observacoes').val(data.observacoes);
            $('#modalEdit').modal('show');
        });
    });
});
</script>
