<div class="nav-scroller box-shadow mb-4"><div class="container"><nav class="nav nav-underline"><a class="nav-link" href="<?= base_url(); ?>app/home"><i class="fas fa-home"></i> Dashboard</a><a class="nav-link active" href="<?= base_url(); ?>pecas/lista"><i class="fas fa-microchip"></i> Peças</a></nav></div></div>
<div role="main" class="container-fluid px-md-5">
<?php $this->load->view('layout/notifications', ['notify_view' => 'riscos', 'msg' => $msg]); ?>
<div class="my-3 p-4 rounded box-shadow"><div class="row align-items-center"><div class="col-md-6"><h5 class="card-title mb-1"><i class="fas fa-microchip mr-2 text-primary"></i> <b>Peças e Componentes</b></h5><p class="text-muted mb-0" style="font-size: 13px;">Controle de peças, estoque e preços.</p></div><div class="col-md-6 text-md-right mt-3 mt-md-0"><button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#modalAdd"><i class="fas fa-plus mr-1"></i> Nova Peça</button></div></div></div>
<div class="p-4 rounded box-shadow" style="background: white;">
<div class="table-responsive">
<table class="table table-hover" id="tbl_pecas"><thead><tr><th>Código</th><th>Nome</th><th>Cat.</th><th>Fabricante</th><th>Qtd</th><th>Estoque</th><th>Preço Custo</th><th>Preço Venda</th><th>Status</th><th class="text-right">Ações</th></tr></thead>
<tbody><?php foreach ($pecas as $p): ?><tr><td style="font-size: 12px;"><?= $p->codigo; ?></td><td><span class="font-weight-bold" style="font-size: 13px;"><?= $p->nome; ?></span></td><td style="font-size: 12px;"><?= $p->categoria_nome ?: '-'; ?></td><td style="font-size: 12px;"><?= $p->fabricante ?: '-'; ?></td><td class="font-weight-bold text-center" style="font-size: 14px; color: <?= $p->quantidade <= $p->quantidade_minima ? '#dc2626' : '#059669'; ?>;"><?= $p->quantidade; ?></td><td><div class="progress" style="height: 6px; width: 60px; border-radius: 10px; background: #f1f5f9;"><div class="progress-bar" role="progressbar" style="width: <?= $p->quantidade_minima > 0 ? min(($p->quantidade / $p->quantidade_minima) * 100, 100) : 50; ?>%; background: <?= $p->quantidade <= $p->quantidade_minima ? '#dc2626' : '#059669'; ?>; border-radius: 10px;"></div></div></td><td style="font-size: 12px;">R$ <?= number_format($p->preco_custo, 2, ',', '.'); ?></td><td style="font-size: 12px;">R$ <?= number_format($p->preco_venda, 2, ',', '.'); ?></td><td><span class="badge badge-pill badge-<?= $p->status == 'ATIVO' ? 'success' : 'secondary'; ?>"><?= $p->status; ?></span></td><td class="text-right">
<button class="btn btn-sm btn-outline-success py-1 px-2 btn-mov" data-id="<?= $p->idpeca; ?>" data-nome="<?= $p->nome; ?>" style="font-size: 11px;" title="Movimentar"><i class="fas fa-exchange-alt"></i></button>
<button class="btn btn-sm btn-outline-primary py-1 px-2 btn-edit" data-id="<?= $p->idpeca; ?>" style="font-size: 11px;"><i class="fas fa-edit"></i></button>
<a href="<?= base_url(); ?>pecas/delete/<?= $p->idpeca; ?>" class="btn btn-sm btn-outline-danger py-1 px-2" style="font-size: 11px;" onclick="return confirm('Excluir?');"><i class="fas fa-trash"></i></a>
</td></tr><?php endforeach; ?></tbody></table></div></div></div>

<div class="modal fade" id="modalAdd" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title"><i class="fas fa-microchip mr-2 text-primary"></i> Nova Peça</h5><button type="button" class="close" data-dismiss="modal"><span>&times;</span></button></div><form method="post" action="<?= base_url(); ?>pecas/adicionar"><div class="modal-body p-4">
<div class="row"><div class="col-md-8"><div class="form-group"><label>Nome</label><input type="text" class="form-control" name="nome" required></div></div><div class="col-md-4"><div class="form-group"><label>Código</label><input type="text" class="form-control" name="codigo" placeholder="Auto"></div></div></div>
<div class="row"><div class="col-md-4"><div class="form-group"><label>Categoria</label><select class="form-control" name="idcategoria"><option value="">Selecione</option><?php foreach ($categorias as $cat): ?><option value="<?= $cat->idcategoria; ?>"><?= $cat->nome; ?></option><?php endforeach; ?></select></div></div><div class="col-md-4"><div class="form-group"><label>Fabricante</label><input type="text" class="form-control" name="fabricante"></div></div><div class="col-md-4"><div class="form-group"><label>Unidade</label><select class="form-control" name="unidade"><option value="un">Unidade</option><option value="cx">Caixa</option><option value="kg">Kg</option><option value="m">Metro</option></select></div></div></div>
<div class="row"><div class="col-md-3"><div class="form-group"><label>Qtd. Estoque</label><input type="number" step="0.01" class="form-control" name="quantidade" value="0"></div></div><div class="col-md-3"><div class="form-group"><label>Qtd. Mínima</label><input type="number" step="0.01" class="form-control" name="quantidade_minima" value="0"></div></div><div class="col-md-3"><div class="form-group"><label>Preço Custo</label><input type="number" step="0.01" class="form-control" name="preco_custo" value="0"></div></div><div class="col-md-3"><div class="form-group"><label>Preço Venda</label><input type="number" step="0.01" class="form-control" name="preco_venda" value="0"></div></div></div>
<div class="row"><div class="col-md-6"><div class="form-group"><label>Localização</label><input type="text" class="form-control" name="localizacao"></div></div><div class="col-md-6"><div class="form-group"><label>Modelo Compatível</label><input type="text" class="form-control" name="modelo_compativel"></div></div></div>
<div class="form-group"><label>Descrição</label><textarea class="form-control" name="descricao" rows="2"></textarea></div>
</div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button><button type="submit" class="btn btn-primary">Salvar</button></div></form></div></div></div>

<div class="modal fade" id="modalEdit" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title"><i class="fas fa-edit mr-2 text-primary"></i> Editar Peça</h5><button type="button" class="close" data-dismiss="modal"><span>&times;</span></button></div><form method="post" action="<?= base_url(); ?>pecas/update"><input type="hidden" name="idpeca" id="edit_id"><div class="modal-body p-4">
<div class="row"><div class="col-md-8"><div class="form-group"><label>Nome</label><input type="text" class="form-control" name="nome" id="edit_nome" required></div></div><div class="col-md-4"><div class="form-group"><label>Código</label><input type="text" class="form-control" name="codigo" id="edit_codigo"></div></div></div>
<div class="row"><div class="col-md-4"><div class="form-group"><label>Categoria</label><select class="form-control" name="idcategoria" id="edit_idcategoria"><option value="">Selecione</option><?php foreach ($categorias as $cat): ?><option value="<?= $cat->idcategoria; ?>"><?= $cat->nome; ?></option><?php endforeach; ?></select></div></div><div class="col-md-4"><div class="form-group"><label>Fabricante</label><input type="text" class="form-control" name="fabricante" id="edit_fabricante"></div></div><div class="col-md-4"><div class="form-group"><label>Unidade</label><select class="form-control" name="unidade" id="edit_unidade"><option value="un">Unidade</option><option value="cx">Caixa</option><option value="kg">Kg</option></select></div></div></div>
<div class="row"><div class="col-md-3"><div class="form-group"><label>Qtd</label><input type="number" step="0.01" class="form-control" name="quantidade" id="edit_quantidade"></div></div><div class="col-md-3"><div class="form-group"><label>Qtd Mín</label><input type="number" step="0.01" class="form-control" name="quantidade_minima" id="edit_quantidade_minima"></div></div><div class="col-md-3"><div class="form-group"><label>Custo</label><input type="number" step="0.01" class="form-control" name="preco_custo" id="edit_preco_custo"></div></div><div class="col-md-3"><div class="form-group"><label>Venda</label><input type="number" step="0.01" class="form-control" name="preco_venda" id="edit_preco_venda"></div></div></div>
<div class="row"><div class="col-md-6"><div class="form-group"><label>Localização</label><input type="text" class="form-control" name="localizacao" id="edit_localizacao"></div></div><div class="col-md-6"><div class="form-group"><label>Modelo Compatível</label><input type="text" class="form-control" name="modelo_compativel" id="edit_modelo_compativel"></div></div></div>
<div class="form-group"><label>Descrição</label><textarea class="form-control" name="descricao" id="edit_descricao" rows="2"></textarea></div>
</div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button><button type="submit" class="btn btn-primary">Atualizar</button></div></form></div></div></div>

<div class="modal fade" id="modalMov" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title"><i class="fas fa-exchange-alt mr-2 text-success"></i> Movimentar <span id="mov_nome"></span></h5><button type="button" class="close" data-dismiss="modal"><span>&times;</span></button></div><form method="post" action="<?= base_url(); ?>pecas/movimentar"><input type="hidden" name="idpeca" id="mov_id"><div class="modal-body p-4">
<div class="row"><div class="col-md-6"><div class="form-group"><label>Tipo</label><select class="form-control" name="tipo_mov"><option value="ENTRADA">Entrada</option><option value="SAIDA">Saída</option></select></div></div><div class="col-md-6"><div class="form-group"><label>Quantidade</label><input type="number" step="0.01" class="form-control" name="quantidade_mov" value="1" required></div></div></div>
</div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button><button type="submit" class="btn btn-success">Confirmar</button></div></form></div></div></div>

<script>
$(document).ready(function() {
    if (!$.fn.DataTable.isDataTable('#tbl_pecas')) $('#tbl_pecas').DataTable({ "info": true, "searching": true, "paging": true, "pageLength": 15, "language": { "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Portuguese.json" } });
    $('.btn-edit').on('click', function() {
        var id = $(this).data('id');
        $.getJSON('<?= base_url(); ?>pecas/get/' + id, function(data) {
            $('#edit_id').val(data.idpeca); $('#edit_nome').val(data.nome); $('#edit_codigo').val(data.codigo);
            $('#edit_idcategoria').val(data.idcategoria); $('#edit_fabricante').val(data.fabricante);
            $('#edit_unidade').val(data.unidade); $('#edit_quantidade').val(data.quantidade);
            $('#edit_quantidade_minima').val(data.quantidade_minima); $('#edit_preco_custo').val(data.preco_custo);
            $('#edit_preco_venda').val(data.preco_venda); $('#edit_localizacao').val(data.localizacao);
            $('#edit_modelo_compativel').val(data.modelo_compativel); $('#edit_descricao').val(data.descricao);
            $('#modalEdit').modal('show');
        });
    });
    $('.btn-mov').on('click', function() {
        $('#mov_id').val($(this).data('id'));
        $('#mov_nome').text($(this).data('nome'));
        $('#modalMov').modal('show');
    });
});
</script>
