<div class="nav-scroller box-shadow mb-4"><div class="container"><nav class="nav nav-underline"><a class="nav-link" href="<?= base_url(); ?>app/home"><i class="fas fa-home"></i> Dashboard</a><a class="nav-link active" href="<?= base_url(); ?>agenda/lista"><i class="fas fa-calendar-alt"></i> Agenda</a></nav></div></div>
<div role="main" class="container-fluid px-md-5">
<?php $this->load->view('layout/notifications', ['notify_view' => 'riscos', 'msg' => $msg]); ?>
<div class="my-3 p-4 rounded box-shadow"><div class="row align-items-center"><div class="col-md-6"><h5 class="card-title mb-1"><i class="fas fa-calendar-alt mr-2 text-primary"></i> <b>Agenda de Eventos</b></h5><p class="text-muted mb-0" style="font-size: 13px;">Visitas técnicas, reuniões e agendamentos.</p></div><div class="col-md-6 text-md-right mt-3 mt-md-0"><button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#modalAdd"><i class="fas fa-plus mr-1"></i> Novo Evento</button></div></div></div>

<div class="row mb-4"><div class="col-md-12">
<div class="p-4 rounded box-shadow" style="background: white;">
<h6 class="card-title mb-3" style="font-size: 14px;"><i class="fas fa-calendar-week mr-2 text-primary"></i> Eventos</h6>
<div class="table-responsive">
<table class="table table-hover" id="tbl_agenda">
<thead><tr><th>Título</th><th>Tipo</th><th>Técnico</th><th>Cliente</th><th>Data/Hora</th><th>Local</th><th>Status</th><th class="text-right">Ações</th></tr></thead>
<tbody><?php foreach ($eventos as $ev): ?><tr><td><span class="font-weight-bold" style="font-size: 13px;"><?= $ev->titulo; ?></span></td><td><span class="badge badge-pill" style="background: <?= $ev->cor; ?>20; color: <?= $ev->cor; ?>;"><?= $ev->tipo; ?></span></td><td style="font-size: 12px;"><?= $ev->tecnico_nome ?: '-'; ?></td><td style="font-size: 12px;"><?= $ev->cliente_nome ?: '-'; ?></td><td style="font-size: 11px;"><?= date('d/m/Y H:i', strtotime($ev->data_inicio)); ?></td><td style="font-size: 12px;"><?= $ev->local ?: '-'; ?></td><td><span class="badge badge-pill badge-<?= $ev->status == 'REALIZADO' ? 'success' : ($ev->status == 'AGENDADO' ? 'primary' : ($ev->status == 'CONFIRMADO' ? 'info' : ($ev->status == 'CANCELADO' ? 'danger' : 'warning'))); ?>"><?= $ev->status; ?></span></td><td class="text-right"><button class="btn btn-sm btn-outline-primary py-1 px-2 btn-edit" data-id="<?= $ev->idevento; ?>"><i class="fas fa-edit"></i></button><a href="<?= base_url(); ?>agenda/delete/<?= $ev->idevento; ?>" class="btn btn-sm btn-outline-danger py-1 px-2" onclick="return confirm('Excluir?');"><i class="fas fa-trash"></i></a></td></tr><?php endforeach; ?></tbody></table></div></div></div></div></div>

<div class="modal fade" id="modalAdd" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title"><i class="fas fa-calendar-plus mr-2 text-primary"></i> Novo Evento</h5><button type="button" class="close" data-dismiss="modal"><span>&times;</span></button></div><form method="post" action="<?= base_url(); ?>agenda/adicionar"><div class="modal-body p-4">
<div class="row"><div class="col-md-8"><div class="form-group"><label>Título</label><input type="text" class="form-control" name="titulo" required></div></div><div class="col-md-4"><div class="form-group"><label>Tipo</label><select class="form-control" name="tipo"><option value="VISITA_TECNICA">Visita Técnica</option><option value="REUNIAO">Reunião</option><option value="MANUTENCAO">Manutenção</option><option value="INSTALACAO">Instalação</option><option value="OUTRO">Outro</option></select></div></div></div>
<div class="row"><div class="col-md-4"><div class="form-group"><label>Data/Hora Início</label><input type="datetime-local" class="form-control" name="data_inicio" required></div></div><div class="col-md-4"><div class="form-group"><label>Data/Hora Fim</label><input type="datetime-local" class="form-control" name="data_fim"></div></div><div class="col-md-4"><div class="form-group"><label>Status</label><select class="form-control" name="status"><option value="AGENDADO">Agendado</option><option value="CONFIRMADO">Confirmado</option><option value="REALIZADO">Realizado</option><option value="CANCELADO">Cancelado</option></select></div></div></div>
<div class="row"><div class="col-md-6"><div class="form-group"><label>Técnico</label><select class="form-control" name="admin_id"><option value="">Selecione</option><?php foreach ($tecnicos as $t): ?><option value="<?= $t->adminid; ?>"><?= $t->nome; ?></option><?php endforeach; ?></select></div></div><div class="col-md-6"><div class="form-group"><label>Cliente</label><select class="form-control" name="cliente_id"><option value="">Selecione</option><?php foreach ($clientes as $c): ?><option value="<?= $c->clientesid; ?>"><?= $c->nome; ?></option><?php endforeach; ?></select></div></div></div>
<div class="row"><div class="col-md-8"><div class="form-group"><label>Local</label><input type="text" class="form-control" name="local" placeholder="Endereço ou local do evento"></div></div><div class="col-md-4"><div class="form-group"><label>Cor</label><input type="color" class="form-control" name="cor" value="#6366f1" style="height: 38px; padding: 4px;"></div></div></div>
<div class="form-group"><label>Descrição</label><textarea class="form-control" name="descricao" rows="2"></textarea></div>
</div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button><button type="submit" class="btn btn-primary">Salvar</button></div></form></div></div></div>

<div class="modal fade" id="modalEdit" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title"><i class="fas fa-edit mr-2 text-primary"></i> Editar Evento</h5><button type="button" class="close" data-dismiss="modal"><span>&times;</span></button></div><form method="post" action="<?= base_url(); ?>agenda/update"><input type="hidden" name="idevento" id="edit_id"><div class="modal-body p-4">
<div class="row"><div class="col-md-8"><div class="form-group"><label>Título</label><input type="text" class="form-control" name="titulo" id="edit_titulo" required></div></div><div class="col-md-4"><div class="form-group"><label>Tipo</label><select class="form-control" name="tipo" id="edit_tipo"><option value="VISITA_TECNICA">Visita Técnica</option><option value="REUNIAO">Reunião</option><option value="MANUTENCAO">Manutenção</option></select></div></div></div>
<div class="row"><div class="col-md-4"><div class="form-group"><label>Início</label><input type="datetime-local" class="form-control" name="data_inicio" id="edit_data_inicio"></div></div><div class="col-md-4"><div class="form-group"><label>Fim</label><input type="datetime-local" class="form-control" name="data_fim" id="edit_data_fim"></div></div><div class="col-md-4"><div class="form-group"><label>Status</label><select class="form-control" name="status" id="edit_status"><option value="AGENDADO">Agendado</option><option value="CONFIRMADO">Confirmado</option><option value="REALIZADO">Realizado</option></select></div></div></div>
<div class="row"><div class="col-md-6"><div class="form-group"><label>Técnico</label><select class="form-control" name="admin_id" id="edit_admin_id"><option value="">Selecione</option><?php foreach ($tecnicos as $t): ?><option value="<?= $t->adminid; ?>"><?= $t->nome; ?></option><?php endforeach; ?></select></div></div><div class="col-md-6"><div class="form-group"><label>Cliente</label><select class="form-control" name="cliente_id" id="edit_cliente_id"><option value="">Selecione</option><?php foreach ($clientes as $c): ?><option value="<?= $c->clientesid; ?>"><?= $c->nome; ?></option><?php endforeach; ?></select></div></div></div>
<div class="row"><div class="col-md-8"><div class="form-group"><label>Local</label><input type="text" class="form-control" name="local" id="edit_local"></div></div><div class="col-md-4"><div class="form-group"><label>Cor</label><input type="color" class="form-control" name="cor" id="edit_cor" value="#6366f1"></div></div></div>
<div class="form-group"><label>Descrição</label><textarea class="form-control" name="descricao" id="edit_descricao" rows="2"></textarea></div>
</div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button><button type="submit" class="btn btn-primary">Atualizar</button></div></form></div></div></div>

<script>
$(document).ready(function() {
    if (!$.fn.DataTable.isDataTable('#tbl_agenda')) $('#tbl_agenda').DataTable({ "info": true, "searching": true, "paging": true, "pageLength": 15, "order": [[4, 'desc']], "language": { "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Portuguese.json" } });
    $('.btn-edit').on('click', function() {
        var id = $(this).data('id');
        $.getJSON('<?= base_url(); ?>agenda/get/' + id, function(data) {
            $('#edit_id').val(data.idevento); $('#edit_titulo').val(data.titulo); $('#edit_tipo').val(data.tipo);
            if (data.data_inicio) $('#edit_data_inicio').val(data.data_inicio.replace(' ', 'T'));
            if (data.data_fim) $('#edit_data_fim').val(data.data_fim.replace(' ', 'T'));
            $('#edit_status').val(data.status); $('#edit_admin_id').val(data.admin_id); $('#edit_cliente_id').val(data.cliente_id);
            $('#edit_local').val(data.local); $('#edit_cor').val(data.cor); $('#edit_descricao').val(data.descricao);
            $('#modalEdit').modal('show');
        });
    });
});
</script>
