<div class="nav-scroller box-shadow mb-4"><div class="container"><nav class="nav nav-underline"><a class="nav-link" href="<?= base_url(); ?>app/home"><i class="fas fa-home"></i> Dashboard</a><a class="nav-link active" href="<?= base_url(); ?>contasareceber/lista"><i class="fas fa-hand-holding-usd"></i> Contas a Receber</a></nav></div></div>
<div role="main" class="container-fluid px-md-5">
<?php $this->load->view('layout/notifications', ['notify_view' => 'riscos', 'msg' => $msg]); ?>
<div class="my-3 p-4 rounded box-shadow"><div class="row align-items-center"><div class="col-md-6"><h5 class="card-title mb-1"><i class="fas fa-hand-holding-usd mr-2 text-primary"></i> <b>Contas a Receber</b></h5><p class="text-muted mb-0" style="font-size: 13px;">Gestão de recebíveis e cobranças.</p></div><div class="col-md-6 text-md-right mt-3 mt-md-0"><button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#modalAdd"><i class="fas fa-plus mr-1"></i> Novo Recebível</button></div></div></div>
<div class="row mb-4"><div class="col-md-6"><div class="p-3 rounded box-shadow" style="background: white;"><span class="text-muted d-block" style="font-size: 10px;">A RECEBER</span><h3 class="font-weight-bold mb-0" style="color: #f59e0b;">R$ <?= number_format($total_pendente, 2, ',', '.'); ?></h3></div></div><div class="col-md-6"><div class="p-3 rounded box-shadow" style="background: white;"><span class="text-muted d-block" style="font-size: 10px;">RECEBIDO</span><h3 class="font-weight-bold mb-0" style="color: #059669;">R$ <?= number_format($total_recebido, 2, ',', '.'); ?></h3></div></div></div>
<div class="p-4 rounded box-shadow" style="background: white;">
<table class="table table-hover" id="tbl_receber"><thead><tr><th>Código</th><th>Cliente</th><th>Descrição</th><th>Valor</th><th>Vencimento</th><th>Recebido</th><th>Status</th><th class="text-right">Ações</th></tr></thead>
<tbody><?php foreach ($receber as $r): ?><tr><td><code><?= $r->codigo; ?></code></td><td style="font-size: 12px;"><?= $r->cliente_nome ?: '-'; ?></td><td><span class="font-weight-bold" style="font-size: 13px;"><?= $r->descricao; ?></span></td><td class="font-weight-bold">R$ <?= number_format($r->valor, 2, ',', '.'); ?></td><td style="font-size: 11px;"><?= $r->data_vencimento ? date('d/m/Y', strtotime($r->data_vencimento)) : '-'; ?></td><td style="font-size: 12px;"><?= $r->valor_recebido ? 'R$ '.number_format($r->valor_recebido, 2, ',', '.') : '-'; ?></td><td><span class="badge badge-pill badge-<?= $r->status == 'PAGO' ? 'success' : ($r->status == 'PENDENTE' ? 'warning' : ($r->status == 'ATRASADO' ? 'danger' : 'secondary')); ?>"><?= $r->status; ?></span></td><td class="text-right"><?php if ($r->status != 'PAGO'): ?><a href="<?= base_url(); ?>contasareceber/baixar/<?= $r->idreceber; ?>" class="btn btn-sm btn-success py-1 px-2" title="Baixar" onclick="return confirm('Confirmar recebimento?');"><i class="fas fa-check"></i></a><?php endif; ?><button class="btn btn-sm btn-primary py-1 px-2 btn-edit" data-id="<?= $r->idreceber; ?>"><i class="fas fa-edit"></i></button><a href="<?= base_url(); ?>contasareceber/delete/<?= $r->idreceber; ?>" class="btn btn-sm btn-danger py-1 px-2" onclick="return confirm('Excluir?');"><i class="fas fa-trash"></i></a></td></tr><?php endforeach; ?></tbody></table></div></div>

<div class="modal fade" id="modalAdd" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title"><i class="fas fa-hand-holding-usd mr-2 text-primary"></i> Novo Recebível</h5><button type="button" class="close" data-dismiss="modal"><span>&times;</span></button></div><form method="post" action="<?= base_url(); ?>contasareceber/adicionar"><div class="modal-body p-3">
<div class="form-group"><label>Código</label><input type="text" class="form-control" name="codigo" value="REC-<?= str_pad(count($receber)+1, 3, '0', STR_PAD_LEFT); ?>" required></div>
<div class="form-group"><label>Cliente</label><select class="form-control" name="clientesid"><option value="">Selecione</option><?php foreach ($clientes as $cl): ?><option value="<?= $cl->clientesid; ?>"><?= $cl->nome; ?></option><?php endforeach; ?></select></div>
<div class="form-group"><label>Descrição</label><input type="text" class="form-control" name="descricao" required></div>
<div class="row"><div class="col-md-6"><div class="form-group"><label>Valor (R$)</label><input type="number" step="0.01" class="form-control" name="valor" required></div></div><div class="col-md-6"><div class="form-group"><label>Data Vencimento</label><input type="date" class="form-control" name="data_vencimento"></div></div></div>
<div class="row"><div class="col-md-6"><div class="form-group"><label>Forma Pagamento</label><select class="form-control" name="forma_pagamento"><option value="BOLETO">Boleto</option><option value="PIX">Pix</option><option value="CARTAO">Cartão</option><option value="TRANSFERENCIA">Transferência</option></select></div></div><div class="col-md-6"><div class="form-group"><label>Status</label><select class="form-control" name="status"><option value="PENDENTE">Pendente</option><option value="PAGO">Pago</option><option value="CANCELADO">Cancelado</option></select></div></div></div>
<div class="form-group"><label>Observações</label><textarea class="form-control" name="observacoes" rows="2"></textarea></div>
</div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button><button type="submit" class="btn btn-primary">Salvar</button></div></form></div></div></div>

<div class="modal fade" id="modalEdit" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title"><i class="fas fa-edit mr-2 text-primary"></i> Editar Recebível</h5><button type="button" class="close" data-dismiss="modal"><span>&times;</span></button></div><form method="post" action="<?= base_url(); ?>contasareceber/update"><input type="hidden" name="idreceber" id="edit_id"><div class="modal-body p-3">
<div class="form-group"><label>Código</label><input type="text" class="form-control" name="codigo" id="edit_codigo" required></div>
<div class="form-group"><label>Cliente</label><select class="form-control" name="clientesid" id="edit_clientesid"><?php foreach ($clientes as $cl): ?><option value="<?= $cl->clientesid; ?>"><?= $cl->nome; ?></option><?php endforeach; ?></select></div>
<div class="form-group"><label>Descrição</label><input type="text" class="form-control" name="descricao" id="edit_descricao" required></div>
<div class="row"><div class="col-md-6"><div class="form-group"><label>Valor</label><input type="number" step="0.01" class="form-control" name="valor" id="edit_valor" required></div></div><div class="col-md-6"><div class="form-group"><label>Vencimento</label><input type="date" class="form-control" name="data_vencimento" id="edit_data_vencimento"></div></div></div>
<div class="row"><div class="col-md-4"><div class="form-group"><label>Recebido</label><input type="number" step="0.01" class="form-control" name="valor_recebido" id="edit_valor_recebido"></div></div><div class="col-md-4"><div class="form-group"><label>Juros</label><input type="number" step="0.01" class="form-control" name="juros" id="edit_juros" value="0"></div></div><div class="col-md-4"><div class="form-group"><label>Multa</label><input type="number" step="0.01" class="form-control" name="multa" id="edit_multa" value="0"></div></div></div>
<div class="row"><div class="col-md-6"><div class="form-group"><label>Data Pagamento</label><input type="date" class="form-control" name="data_pagamento" id="edit_data_pagamento"></div></div><div class="col-md-6"><div class="form-group"><label>Status</label><select class="form-control" name="status" id="edit_status"><option value="PENDENTE">Pendente</option><option value="PAGO">Pago</option><option value="ATRASADO">Atrasado</option><option value="CANCELADO">Cancelado</option></select></div></div></div>
<div class="form-group"><label>Observações</label><textarea class="form-control" name="observacoes" id="edit_observacoes" rows="2"></textarea></div>
</div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button><button type="submit" class="btn btn-primary">Atualizar</button></div></form></div></div></div>

<script>
$(document).ready(function() {
    if (!$.fn.DataTable.isDataTable('#tbl_receber')) $('#tbl_receber').DataTable({ "info": true, "searching": true, "paging": true, "pageLength": 15, "order": [[4, 'desc']], "language": { "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Portuguese.json" } });
    $('.btn-edit').on('click', function() {
        $.getJSON('<?= base_url(); ?>contasareceber/get/' + $(this).data('id'), function(data) {
            $('#edit_id').val(data.idreceber); $('#edit_codigo').val(data.codigo); $('#edit_clientesid').val(data.clientesid);
            $('#edit_descricao').val(data.descricao); $('#edit_valor').val(data.valor);
            if (data.data_vencimento) $('#edit_data_vencimento').val(data.data_vencimento);
            $('#edit_valor_recebido').val(data.valor_recebido); $('#edit_juros').val(data.juros); $('#edit_multa').val(data.multa);
            if (data.data_pagamento) $('#edit_data_pagamento').val(data.data_pagamento);
            $('#edit_status').val(data.status); $('#edit_observacoes').val(data.observacoes);
            $('#modalEdit').modal('show');
        });
    });
});
</script>
